spring:
  datasource:
    url: jdbc:mysql://mysql-blog:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
  devtools:
    add-properties: false

server:
  port: 80
